"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { motion } from "motion/react";
import { api } from "@/lib/client/api";
import type { AiBreakdown as Breakdown, Post } from "@/lib/types";

const PROVIDER_LABEL: Record<Breakdown["provider"], string> = {
  anthropic: "Claude",
  openai: "OpenAI",
  gemini: "Gemini",
  heuristic: "Built-in analysis",
};

export function AiBreakdown({ post }: { post: Post }) {
  const queryClient = useQueryClient();
  const mutation = useMutation({
    mutationFn: (refresh: boolean) => api<Breakdown>(`/api/posts/${post.id}/breakdown${refresh ? "?refresh=1" : ""}`, { method: "POST" }),
    onSuccess: (breakdown) => queryClient.setQueryData<Post>(["post", post.id], (old) => (old ? { ...old, aiBreakdown: breakdown } : old)),
  });
  const breakdown = mutation.data ?? post.aiBreakdown;

  return (
    <section className="border-border rounded-md border p-4">
      <div className="flex items-center gap-2">
        <span className="border-accent/40 bg-accent/12 text-accent grid size-7 place-items-center rounded-md border">
          <Sparkles className="size-4" />
        </span>
        <h3 className="text-sm font-semibold">Why it went viral</h3>
        {breakdown && (
          <button
            onClick={() => mutation.mutate(true)}
            disabled={mutation.isPending}
            className="text-muted hover:bg-surface hover:text-foreground ml-auto grid size-7 place-items-center rounded-lg disabled:opacity-40"
            aria-label="Regenerate breakdown"
          >
            <RefreshCw className={`size-3.5 ${mutation.isPending ? "animate-spin" : ""}`} />
          </button>
        )}
      </div>

      {!breakdown && (
        <button onClick={() => mutation.mutate(false)} disabled={mutation.isPending} className="btn-primary mt-3 w-full">
          {mutation.isPending ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
          {mutation.isPending ? "Analyzing post…" : "Generate AI breakdown"}
        </button>
      )}

      {mutation.isError && <p className="mt-2 text-sm text-red-500">{mutation.error.message}</p>}

      {breakdown && (
        <>
          <ul className="mt-3 space-y-2">
            {breakdown.bullets.map((bullet, i) => (
              <motion.li
                key={bullet}
                initial={{ opacity: 0, x: -6 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.06 }}
                className="flex gap-2 text-sm leading-relaxed"
              >
                <span className="bg-accent mt-2 size-1.5 shrink-0 rounded-full" />
                <span>{bullet}</span>
              </motion.li>
            ))}
          </ul>
          <p className="text-muted mt-3 text-[11px]">Generated by {PROVIDER_LABEL[breakdown.provider]}</p>
        </>
      )}
    </section>
  );
}
